# Site settings
title: Scraping Nerd
email: admin@scrapingnerd.com
description: >-
  Deep dives into advanced web scraping techniques, APIs, and no-code data
  extraction for TikTok, X.com, and more. Tutorials by Novi Develop.
baseurl: ""
url: "https://scrapingnerd.com"
twitter_username: scrapingnerd
github_username: scrapingnerd
author: Novi Develop

# Custom variables
tagline: "Advanced Data Extraction"
hero_title: "Web Scraping Mastery "
hero_highlight: "For Everyone"

# Build settings
layouts_dir: shared/_layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink style
permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Novi Develop"
